const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {config,pagador}=require('./ailos-fixtures.cjs'),C=require('../public/ailos-cnab');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('transação, autorização, reserva repetida, isolamento da homologação e baixa compartilhada',async()=>{
 const {PGlite}=await import('@electric-sql/pglite');const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;create table profiles(id uuid primary key,ativo boolean,tipo text,setor text);insert into profiles values('${id(1)}',true,'Financeiro','Financeiro'),('${id(2)}',true,'Comercial','Comercial'),('${id(3)}',false,'Administrador','Diretoria');create table fin_receb_clientes(id uuid primary key,nome text,cpf_cnpj text,ativo boolean);create table fin_receb_parcelas(id uuid primary key,cliente_id uuid,numero int,vencimento date,valor_previsto numeric,juros numeric default 0,multa numeric default 0,nosso_numero text,documento text,linha_digitavel text,status text,pago_em date,valor_liquidado numeric default 0,diferenca numeric,ativo boolean,versao bigint default 1);create function public.versionar() returns trigger language plpgsql as $$begin new.versao=old.versao+1;return new;end$$;create trigger versao before update on fin_receb_parcelas for each row execute function versionar();insert into fin_receb_clientes values('${id(10)}','${pagador.nome}','${pagador.cpf_cnpj}',true);insert into fin_receb_parcelas(id,cliente_id,numero,vencimento,valor_previsto,status,ativo) values('${id(20)}','${id(10)}',1,current_date+10,100,'Pendente',true),('${id(21)}','${id(10)}',2,current_date+20,150,'Pendente',true);`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/ailos-cobranca.sql'),'utf8'));
 const login=async n=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${id(n)}',false);set role authenticated;`);
 const rpc=async(a,d={})=>(await db.query('select public.financeiro_ailos($1,$2) as data',[a,JSON.stringify(d)])).rows[0].data;
 await login(2);await assert.rejects(rpc('painel'),/permissão/);await login(3);await assert.rejects(rpc('painel'),/permissão/);await db.exec('reset role;set role anon;');await assert.rejects(rpc('painel'),/permission denied/);await login(1);await assert.rejects(db.query('select * from ailos_privado.boletos'),/permission denied/);
 await rpc('configurar',{config,ultimo_boleto:253,ultima_remessa:0});await rpc('pagador',{cliente_id:id(10),pagador});
 const prep={id:id(30),parcelas:[{id:id(20),versao:1}]};let r=await rpc('preparar',prep);assert.equal(r.boletos[0].nosso_numero,'02206658000000254');assert.deepEqual(await rpc('preparar',prep),r);await assert.rejects(rpc('preparar',{...prep,id:id(31)}),/reservada/);let out=C.remessa(r);await rpc('finalizar',{id:r.id,...out});await rpc('finalizar',{id:r.id,...out});await db.exec('reset role');assert.equal((await db.query('select nosso_numero from fin_receb_parcelas where id=$1',[id(20)])).rows[0].nosso_numero,null);await login(1);
 await rpc('configurar',{config:{...config,ambiente:'producao',homologado:true,protocolo:'TESTE HOMOLOGADO'},ultimo_boleto:254,ultima_remessa:1});r=await rpc('preparar',{...prep,id:id(32)});out=C.remessa(r);await rpc('finalizar',{id:r.id,...out});await db.exec('reset role');let p=(await db.query('select * from fin_receb_parcelas where id=$1',[id(20)])).rows[0];assert.equal(p.nosso_numero,'02206658000000255');assert.equal(p.versao,2);assert.equal(p.status,'Pendente');await login(1);
 const date=(await db.query('select current_date::text as d')).rows[0].d;const event={nosso_numero:r.boletos[0].nosso_numero,documento:r.boletos[0].documento,valor_centavos:10000,vencimento:r.boletos[0].vencimento,cpf_cnpj:pagador.cpf_cnpj,ocorrencia:'02',motivos:'0000000000',pago_centavos:0,liquido_centavos:0,data:date,credito:date};
 await rpc('retorno',{hash:'a'.repeat(64),nome:'entrada.ret',ambiente:'producao',eventos:[event]});assert.equal((await rpc('painel')).boletos.find(b=>b.nosso_numero===event.nosso_numero).estado,'Registrado');
 await assert.rejects(rpc('retorno',{hash:'b'.repeat(64),nome:'erro.ret',ambiente:'producao',eventos:[{...event,ocorrencia:'06',pago_centavos:10000},{...event,nosso_numero:'02206658000000999'}]}),/não emitido/);
 assert.equal((await rpc('painel')).boletos.find(b=>b.nosso_numero===event.nosso_numero).estado,'Registrado');
 const pay={hash:'c'.repeat(64),nome:'pago.ret',ambiente:'producao',eventos:[{...event,ocorrencia:'06',pago_centavos:10000,liquido_centavos:9800}]};await rpc('retorno',pay);assert.equal((await rpc('retorno',pay)).repetido,true);assert.equal((await rpc('retorno',{...pay,hash:'d'.repeat(64)})).processados,0);await db.exec('reset role');p=(await db.query('select * from fin_receb_parcelas where id=$1',[id(20)])).rows[0];assert.equal(p.status,'Pago');assert.equal(Number(p.valor_liquidado),100);assert.equal(p.versao,3);
 }finally{await db.close();}
});
